import os


MONGO_URL = os.getenv("MONGO_URL")
FREECURRENCY_API_TOKEN = os.getenv("FREECURRENCY_API_TOKEN")
FUNDAMENTAL_ANALYSIS_API_KEY = os.getenv("FUNDAMENTAL_ANALYSIS_API_KEY")
REDIS_URL = os.getenv("REDIS_URL")
